version: '3.8'

services:
  stargzr:
    #build: .
    image: omersadikovic/stargzr:latest
    container_name: stargzr
    ports:
      - "8083:8083"
    volumes:
      # CHANGE THIS PATH to your media folder location
      - ./media:/app/media:ro
    environment:
      - MEDIA_PATH=/app/media
    restart: unless-stopped